const cadenasFavoritos =
[
  {
    "sd_epg": true,
    "sd_fuente": "",
    "sd_id": "86981",
    "sd_nombre": "#0 HD",
    "sd_numero": "",
    "tvh_id": "CEROHD.es",
    "tvh_m3u": false,
    "tvh_nombre": "#0 HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": true,
    "sd_fuente": "",
    "sd_id": "109803",
    "sd_nombre": "#Vamos",
    "sd_numero": "",
    "tvh_id": "VAMOS.es",
    "tvh_m3u": false,
    "tvh_nombre": "#Vamos",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "90340",
    "sd_nombre": "324",
    "sd_numero": "",
    "tvh_id": "324CAT.es",
    "tvh_m3u": false,
    "tvh_nombre": "324",
    "tvh_tag": ""
  },
  {
    "sd_epg": true,
    "sd_fuente": "",
    "sd_id": "87036",
    "sd_nombre": "AMC",
    "sd_numero": "",
    "tvh_id": "AMCESP.es",
    "tvh_m3u": false,
    "tvh_nombre": "AMC",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "102742",
    "sd_nombre": "AMC +2 HD",
    "sd_numero": "",
    "tvh_id": "AMCE2HD.es",
    "tvh_m3u": false,
    "tvh_nombre": "AMC +2 HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "87057",
    "sd_nombre": "AMC HD",
    "sd_numero": "",
    "tvh_id": "AMCESHD.es",
    "tvh_m3u": false,
    "tvh_nombre": "AMC HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "53426",
    "sd_nombre": "Andalucia TV",
    "sd_numero": "",
    "tvh_id": "ANDALTV.es",
    "tvh_m3u": false,
    "tvh_nombre": "Andalucia TV",
    "tvh_tag": ""
  },
  {
    "sd_epg": true,
    "sd_fuente": "",
    "sd_id": "90309",
    "sd_nombre": "Antena 3",
    "sd_numero": "",
    "tvh_id": "ANTENA3.es",
    "tvh_m3u": false,
    "tvh_nombre": "Antena 3",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "91176",
    "sd_nombre": "Antena 3 HD",
    "sd_numero": "",
    "tvh_id": "ANT3SPH.es",
    "tvh_m3u": false,
    "tvh_nombre": "Antena 3 HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "86951",
    "sd_nombre": "Aragon TV",
    "sd_numero": "",
    "tvh_id": "ARAGON.es",
    "tvh_m3u": false,
    "tvh_nombre": "Aragon TV",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "96446",
    "sd_nombre": "Atreseries",
    "sd_numero": "",
    "tvh_id": "ATSRIES.es",
    "tvh_m3u": false,
    "tvh_nombre": "Atreseries",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "102943",
    "sd_nombre": "Atreseries HD",
    "sd_numero": "",
    "tvh_id": "ATSESHD.es",
    "tvh_m3u": false,
    "tvh_nombre": "Atreseries HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": true,
    "sd_fuente": "",
    "sd_id": "82178",
    "sd_nombre": "AXN",
    "sd_numero": "",
    "tvh_id": "AXNESPP.es",
    "tvh_m3u": false,
    "tvh_nombre": "AXN",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "86996",
    "sd_nombre": "AXN HD",
    "sd_numero": "",
    "tvh_id": "AXNHDSP.es",
    "tvh_m3u": false,
    "tvh_nombre": "AXN HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "87047",
    "sd_nombre": "AXN White",
    "sd_numero": "",
    "tvh_id": "AXNWESP.es",
    "tvh_m3u": false,
    "tvh_nombre": "AXN White",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "91177",
    "sd_nombre": "AXN White HD",
    "sd_numero": "",
    "tvh_id": "AXNWHHD.es",
    "tvh_m3u": false,
    "tvh_nombre": "AXN White HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "86915",
    "sd_nombre": "Baby TV",
    "sd_numero": "",
    "tvh_id": "BABYTVS.es",
    "tvh_m3u": false,
    "tvh_nombre": "Baby TV",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "99701",
    "sd_nombre": "Be Mad TV",
    "sd_numero": "",
    "tvh_id": "BEMAD.es",
    "tvh_m3u": false,
    "tvh_nombre": "Be Mad TV",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "102848",
    "sd_nombre": "Be Mad TV HD",
    "sd_numero": "",
    "tvh_id": "BEMADHD.es",
    "tvh_m3u": false,
    "tvh_nombre": "Be Mad TV HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "100497",
    "sd_nombre": "BeIN LaLiga",
    "sd_numero": "",
    "tvh_id": "BELIGA.es",
    "tvh_m3u": false,
    "tvh_nombre": "BeIN LaLiga",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "102850",
    "sd_nombre": "BeIN LaLiga HD",
    "sd_numero": "",
    "tvh_id": "BELIGHD.es",
    "tvh_m3u": false,
    "tvh_nombre": "BeIN LaLiga HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "102942",
    "sd_nombre": "beIN Sports HD",
    "sd_numero": "",
    "tvh_id": "BEINESH.es",
    "tvh_m3u": false,
    "tvh_nombre": "beIN Sports HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "91145",
    "sd_nombre": "Blaze",
    "sd_numero": "",
    "tvh_id": "BLAZEES.es",
    "tvh_m3u": false,
    "tvh_nombre": "Blaze",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "86956",
    "sd_nombre": "Boing",
    "sd_numero": "",
    "tvh_id": "BOINGE.es",
    "tvh_m3u": false,
    "tvh_nombre": "Boing",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "90352",
    "sd_nombre": "Calle 13 Universal",
    "sd_numero": "",
    "tvh_id": "CALL13.es",
    "tvh_m3u": false,
    "tvh_nombre": "Calle 13 Universal",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "91179",
    "sd_nombre": "Calle 13 Universal HD",
    "sd_numero": "",
    "tvh_id": "CALLEHD.es",
    "tvh_m3u": false,
    "tvh_nombre": "Calle 13 Universal HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "90353",
    "sd_nombre": "Canal 24H",
    "sd_numero": "",
    "tvh_id": "CAN24H.es",
    "tvh_m3u": false,
    "tvh_nombre": "Canal 24H",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "90332",
    "sd_nombre": "Canal Cocina",
    "sd_numero": "",
    "tvh_id": "COCINA.es",
    "tvh_m3u": false,
    "tvh_nombre": "Canal Cocina",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "97471",
    "sd_nombre": "Canal Cocina HD",
    "sd_numero": "",
    "tvh_id": "COCINHD.es",
    "tvh_m3u": false,
    "tvh_nombre": "Canal Cocina HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "98499",
    "sd_nombre": "Canal de las Estrellas",
    "sd_numero": "",
    "tvh_id": "CESTREL.es",
    "tvh_m3u": false,
    "tvh_nombre": "Canal de las Estrellas",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "87087",
    "sd_nombre": "Canal Extremadura",
    "sd_numero": "",
    "tvh_id": "EXTMADU.es",
    "tvh_m3u": false,
    "tvh_nombre": "Canal Extremadura",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "53602",
    "sd_nombre": "Canal Hollywood",
    "sd_numero": "",
    "tvh_id": "CANHOLL.es",
    "tvh_m3u": false,
    "tvh_nombre": "Canal Hollywood",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "102751",
    "sd_nombre": "Canal Hollywood +2 HD",
    "sd_numero": "",
    "tvh_id": "CANH2HD.es",
    "tvh_m3u": false,
    "tvh_nombre": "Canal Hollywood +2 HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "97479",
    "sd_nombre": "Canal Hollywood HD",
    "sd_numero": "",
    "tvh_id": "HOLWHD.es",
    "tvh_m3u": false,
    "tvh_nombre": "Canal Hollywood HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "53736",
    "sd_nombre": "Canal Panda",
    "sd_numero": "",
    "tvh_id": "CANLPAN.es",
    "tvh_m3u": false,
    "tvh_nombre": "Canal Panda",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "90347",
    "sd_nombre": "Canal Super 3",
    "sd_numero": "",
    "tvh_id": "CANSUP3.es",
    "tvh_m3u": false,
    "tvh_nombre": "Canal Super 3",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "53808",
    "sd_nombre": "Canal Sur",
    "sd_numero": "",
    "tvh_id": "CANLSUR.es",
    "tvh_m3u": false,
    "tvh_nombre": "Canal Sur",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "53810",
    "sd_nombre": "Canal Sur 2",
    "sd_numero": "",
    "tvh_id": "CANLSR2.es",
    "tvh_m3u": false,
    "tvh_nombre": "Canal Sur 2",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "97477",
    "sd_nombre": "Canal Sur HD",
    "sd_numero": "",
    "tvh_id": "CNSURHD.es",
    "tvh_m3u": false,
    "tvh_nombre": "Canal Sur HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "90361",
    "sd_nombre": "Castilla-La Mancha Media",
    "sd_numero": "",
    "tvh_id": "CMM.es",
    "tvh_m3u": false,
    "tvh_nombre": "Castilla-La Mancha Media",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "97478",
    "sd_nombre": "Castilla-La Mancha Media HD",
    "sd_numero": "",
    "tvh_id": "CMMHD.es",
    "tvh_m3u": false,
    "tvh_nombre": "Castilla-La Mancha Media HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "86992",
    "sd_nombre": "Caza y Pesca",
    "sd_numero": "",
    "tvh_id": "CAZPES.es",
    "tvh_m3u": false,
    "tvh_nombre": "Caza y Pesca",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "105552",
    "sd_nombre": "Caza y Pesca HD",
    "sd_numero": "",
    "tvh_id": "CAZPESH.es",
    "tvh_m3u": false,
    "tvh_nombre": "Caza y Pesca HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "86931",
    "sd_nombre": "Clan TVE",
    "sd_numero": "",
    "tvh_id": "CLANTVE.es",
    "tvh_m3u": false,
    "tvh_nombre": "Clan TVE",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "106102",
    "sd_nombre": "Clan TVE HD",
    "sd_numero": "",
    "tvh_id": "CLANHD.es",
    "tvh_m3u": false,
    "tvh_nombre": "Clan TVE HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "90331",
    "sd_nombre": "CNN",
    "sd_numero": "",
    "tvh_id": "CNNESP.es",
    "tvh_m3u": false,
    "tvh_nombre": "CNN",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "56309",
    "sd_nombre": "Comedy Central",
    "sd_numero": "",
    "tvh_id": "PRCMSPN.es",
    "tvh_m3u": false,
    "tvh_nombre": "Comedy Central",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "91277",
    "sd_nombre": "Comedy Central HD",
    "sd_numero": "",
    "tvh_id": "CMDYESH.es",
    "tvh_m3u": false,
    "tvh_nombre": "Comedy Central HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "102744",
    "sd_nombre": "Cosmo +2 HD",
    "sd_numero": "",
    "tvh_id": "COSP2HD.es",
    "tvh_m3u": false,
    "tvh_nombre": "Cosmo +2 HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "55940",
    "sd_nombre": "Cosmopolitan TV",
    "sd_numero": "",
    "tvh_id": "COSTVES.es",
    "tvh_m3u": false,
    "tvh_nombre": "Cosmopolitan TV",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "87061",
    "sd_nombre": "Cosmopolitan TV HD",
    "sd_numero": "",
    "tvh_id": "COSESPH.es",
    "tvh_m3u": false,
    "tvh_nombre": "Cosmopolitan TV HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "86927",
    "sd_nombre": "Crimen e Investigación",
    "sd_numero": "",
    "tvh_id": "CRINV.es",
    "tvh_m3u": false,
    "tvh_nombre": "Crimen e Investigación",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "64648",
    "sd_nombre": "Cuatro",
    "sd_numero": "",
    "tvh_id": "CUATRO.es",
    "tvh_m3u": false,
    "tvh_nombre": "Cuatro",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "91199",
    "sd_nombre": "Cuatro HD",
    "sd_numero": "",
    "tvh_id": "CUATRHD.es",
    "tvh_m3u": false,
    "tvh_nombre": "Cuatro HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "90324",
    "sd_nombre": "Dark",
    "sd_numero": "",
    "tvh_id": "DARKSPA.es",
    "tvh_m3u": false,
    "tvh_nombre": "Dark",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "53570",
    "sd_nombre": "Dark/Dorcel TV",
    "sd_numero": "",
    "tvh_id": "DORCESP.es",
    "tvh_m3u": false,
    "tvh_nombre": "Dark/Dorcel TV",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "87012",
    "sd_nombre": "Decasa",
    "sd_numero": "",
    "tvh_id": "DECASA.es",
    "tvh_m3u": false,
    "tvh_nombre": "Decasa",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "102745",
    "sd_nombre": "Decasa HD",
    "sd_numero": "",
    "tvh_id": "DECASHD.es",
    "tvh_m3u": false,
    "tvh_nombre": "Decasa HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "87044",
    "sd_nombre": "Discovery Channel",
    "sd_numero": "",
    "tvh_id": "DISCHIB.es",
    "tvh_m3u": false,
    "tvh_nombre": "Discovery Channel",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "97470",
    "sd_nombre": "Discovery Channel HD",
    "sd_numero": "",
    "tvh_id": "DISHDES.es",
    "tvh_m3u": false,
    "tvh_nombre": "Discovery Channel HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "53439",
    "sd_nombre": "Disney Channel",
    "sd_numero": "",
    "tvh_id": "DISESP.es",
    "tvh_m3u": false,
    "tvh_nombre": "Disney Channel",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "102747",
    "sd_nombre": "Disney Channel +2",
    "sd_numero": "",
    "tvh_id": "DISESP2.es",
    "tvh_m3u": false,
    "tvh_nombre": "Disney Channel +2",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "87058",
    "sd_nombre": "Disney Channel HD",
    "sd_numero": "",
    "tvh_id": "DISESPH.es",
    "tvh_m3u": false,
    "tvh_nombre": "Disney Channel HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "87041",
    "sd_nombre": "Disney Junior",
    "sd_numero": "",
    "tvh_id": "DJRESP.es",
    "tvh_m3u": false,
    "tvh_nombre": "Disney Junior",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "86911",
    "sd_nombre": "Disney XD",
    "sd_numero": "",
    "tvh_id": "DISXDE.es",
    "tvh_m3u": false,
    "tvh_nombre": "Disney XD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "102749",
    "sd_nombre": "Disney XD +2",
    "sd_numero": "",
    "tvh_id": "DISXDE2.es",
    "tvh_m3u": false,
    "tvh_nombre": "Disney XD +2",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "91202",
    "sd_nombre": "Disney XD HD",
    "sd_numero": "",
    "tvh_id": "DISNXHD.es",
    "tvh_m3u": false,
    "tvh_nombre": "Disney XD HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "87038",
    "sd_nombre": "Divinity",
    "sd_numero": "",
    "tvh_id": "DIVINIT.es",
    "tvh_m3u": false,
    "tvh_nombre": "Divinity",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "99862",
    "sd_nombre": "DKiss",
    "sd_numero": "",
    "tvh_id": "DKISS.es",
    "tvh_m3u": false,
    "tvh_nombre": "DKiss",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "90316",
    "sd_nombre": "DMAX",
    "sd_numero": "",
    "tvh_id": "DISCMAX.es",
    "tvh_m3u": false,
    "tvh_nombre": "DMAX",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "87042",
    "sd_nombre": "Energy",
    "sd_numero": "",
    "tvh_id": "ENERGYE.es",
    "tvh_m3u": false,
    "tvh_nombre": "Energy",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "96553",
    "sd_nombre": "EuronewsNBC ",
    "sd_numero": "",
    "tvh_id": "EUNEWSP.es",
    "tvh_m3u": false,
    "tvh_nombre": "EuronewsNBC ",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "86917",
    "sd_nombre": "Eurosport 1",
    "sd_numero": "",
    "tvh_id": "EUSPESP.es",
    "tvh_m3u": false,
    "tvh_nombre": "Eurosport 1",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "91198",
    "sd_nombre": "Eurosport 1 HD",
    "sd_numero": "",
    "tvh_id": "EURSPHD.es",
    "tvh_m3u": false,
    "tvh_nombre": "Eurosport 1 HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "90365",
    "sd_nombre": "Eurosport 2",
    "sd_numero": "",
    "tvh_id": "EUROSPS.es",
    "tvh_m3u": false,
    "tvh_nombre": "Eurosport 2",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "108370",
    "sd_nombre": "Eurosport 2 HD",
    "sd_numero": "",
    "tvh_id": "ES2ESP.es",
    "tvh_m3u": false,
    "tvh_nombre": "Eurosport 2 HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "90362",
    "sd_nombre": "Extreme Sports",
    "sd_numero": "",
    "tvh_id": "EXTRMSP.es",
    "tvh_m3u": false,
    "tvh_nombre": "Extreme Sports",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "78991",
    "sd_nombre": "Factoría de Ficción",
    "sd_numero": "",
    "tvh_id": "FDFS.es",
    "tvh_m3u": false,
    "tvh_nombre": "Factoría de Ficción",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "81785",
    "sd_nombre": "FOX",
    "sd_numero": "",
    "tvh_id": "FOXESP.es",
    "tvh_m3u": false,
    "tvh_nombre": "FOX",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "102750",
    "sd_nombre": "FOX +2 HD",
    "sd_numero": "",
    "tvh_id": "FOXE2HD.es",
    "tvh_m3u": false,
    "tvh_nombre": "FOX +2 HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "87056",
    "sd_nombre": "Fox HD",
    "sd_numero": "",
    "tvh_id": "FOXESHD.es",
    "tvh_m3u": false,
    "tvh_nombre": "Fox HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "91201",
    "sd_nombre": "Fox Life HD",
    "sd_numero": "",
    "tvh_id": "FOXLIHD.es",
    "tvh_m3u": false,
    "tvh_nombre": "Fox Life HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "87097",
    "sd_nombre": "Galicia TV Europa",
    "sd_numero": "",
    "tvh_id": "GALTVE.es",
    "tvh_m3u": false,
    "tvh_nombre": "Galicia TV Europa",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "90356",
    "sd_nombre": "GOL TV",
    "sd_numero": "",
    "tvh_id": "GOLTVES.es",
    "tvh_m3u": false,
    "tvh_nombre": "GOL TV",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "91279",
    "sd_nombre": "Gol TV HD",
    "sd_numero": "",
    "tvh_id": "GOLTVSH.es",
    "tvh_m3u": false,
    "tvh_nombre": "Gol TV HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "90350",
    "sd_nombre": "Historia",
    "sd_numero": "",
    "tvh_id": "HISTSPA.es",
    "tvh_m3u": false,
    "tvh_nombre": "Historia",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "97473",
    "sd_nombre": "Historia HD",
    "sd_numero": "",
    "tvh_id": "HISHDES.es",
    "tvh_m3u": false,
    "tvh_nombre": "Historia HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "90336",
    "sd_nombre": "IB3",
    "sd_numero": "",
    "tvh_id": "IB3.es",
    "tvh_m3u": false,
    "tvh_nombre": "IB3",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "109884",
    "sd_nombre": "IB3 HD",
    "sd_numero": "",
    "tvh_id": "IB3HD.es",
    "tvh_m3u": false,
    "tvh_nombre": "IB3 HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "96790",
    "sd_nombre": "Iberalia",
    "sd_numero": "",
    "tvh_id": "IBRALIA.es",
    "tvh_m3u": false,
    "tvh_nombre": "Iberalia",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "102752",
    "sd_nombre": "Iberalia HD",
    "sd_numero": "",
    "tvh_id": "IBRALHD.es",
    "tvh_m3u": false,
    "tvh_nombre": "Iberalia HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "86928",
    "sd_nombre": "Intereconomia TV",
    "sd_numero": "",
    "tvh_id": "INTRCON.es",
    "tvh_m3u": false,
    "tvh_nombre": "Intereconomia TV",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "86913",
    "sd_nombre": "La 1",
    "sd_numero": "",
    "tvh_id": "LA1.es",
    "tvh_m3u": false,
    "tvh_nombre": "La 1",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "91203",
    "sd_nombre": "La 1 HD",
    "sd_numero": "",
    "tvh_id": "LA1HD.es",
    "tvh_m3u": false,
    "tvh_nombre": "La 1 HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "86914",
    "sd_nombre": "La 2",
    "sd_numero": "",
    "tvh_id": "LA2.es",
    "tvh_m3u": false,
    "tvh_nombre": "La 2",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "91206",
    "sd_nombre": "La 2 HD",
    "sd_numero": "",
    "tvh_id": "LA2HD.es",
    "tvh_m3u": false,
    "tvh_nombre": "La 2 HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "90355",
    "sd_nombre": "La 7 Televisión Región de Murcia",
    "sd_numero": "",
    "tvh_id": "7RM.es",
    "tvh_m3u": false,
    "tvh_nombre": "La 7 Televisión Región de Murcia",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "86933",
    "sd_nombre": "La Otra",
    "sd_numero": "",
    "tvh_id": "TSATOTR.es",
    "tvh_m3u": false,
    "tvh_nombre": "La Otra",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "64649",
    "sd_nombre": "La Sexta",
    "sd_numero": "",
    "tvh_id": "LASEXTA.es",
    "tvh_m3u": false,
    "tvh_nombre": "La Sexta",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "97481",
    "sd_nombre": "La Sexta HD",
    "sd_numero": "",
    "tvh_id": "SEXTHD.es",
    "tvh_m3u": false,
    "tvh_nombre": "La Sexta HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "96453",
    "sd_nombre": "Mega",
    "sd_numero": "",
    "tvh_id": "MEGASPA.es",
    "tvh_m3u": false,
    "tvh_nombre": "Mega",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "102753",
    "sd_nombre": "Mega HD",
    "sd_numero": "",
    "tvh_id": "MEGAEHD.es",
    "tvh_m3u": false,
    "tvh_nombre": "Mega HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "90351",
    "sd_nombre": "Mezzo",
    "sd_numero": "",
    "tvh_id": "MEZESP.es",
    "tvh_m3u": false,
    "tvh_nombre": "Mezzo",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "91183",
    "sd_nombre": "Movistar Acción HD",
    "sd_numero": "",
    "tvh_id": "MACCIHD.es",
    "tvh_m3u": false,
    "tvh_nombre": "Movistar Acción HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "86948",
    "sd_nombre": "Movistar Cine Ñ",
    "sd_numero": "",
    "tvh_id": "MCINEN.es",
    "tvh_m3u": false,
    "tvh_nombre": "Movistar Cine Ñ",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "91382",
    "sd_nombre": "Movistar CineDoc&Roll HD",
    "sd_numero": "",
    "tvh_id": "MDOCHD.es",
    "tvh_m3u": false,
    "tvh_nombre": "Movistar CineDoc&Roll HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "91184",
    "sd_nombre": "Movistar Comedia HD",
    "sd_numero": "",
    "tvh_id": "MCOMHD.es",
    "tvh_m3u": false,
    "tvh_nombre": "Movistar Comedia HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "87010",
    "sd_nombre": "Movistar Deportes HD",
    "sd_numero": "",
    "tvh_id": "MDEP1HD.es",
    "tvh_m3u": false,
    "tvh_nombre": "Movistar Deportes HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "87011",
    "sd_nombre": "Movistar Drama HD",
    "sd_numero": "",
    "tvh_id": "MDRAMHD.es",
    "tvh_m3u": false,
    "tvh_nombre": "Movistar Drama HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "102940",
    "sd_nombre": "Movistar Estrenos HD",
    "sd_numero": "",
    "tvh_id": "MESTHD.es",
    "tvh_m3u": false,
    "tvh_nombre": "Movistar Estrenos HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": true,
    "sd_fuente": "",
    "sd_id": "102938",
    "sd_nombre": "Movistar Fórmula 1 HD",
    "sd_numero": "",
    "tvh_id": "MFOR1HD.es",
    "tvh_m3u": false,
    "tvh_nombre": "Movistar Fórmula 1 HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "91190",
    "sd_nombre": "Movistar Golf HD",
    "sd_numero": "",
    "tvh_id": "MGOLFHD.es",
    "tvh_m3u": false,
    "tvh_nombre": "Movistar Golf HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "109474",
    "sd_nombre": "Movistar Liga de Campeones",
    "sd_numero": "",
    "tvh_id": "LIGCAMP.es",
    "tvh_m3u": false,
    "tvh_nombre": "Movistar Liga de Campeones",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "102939",
    "sd_nombre": "Movistar Moto GP HD",
    "sd_numero": "",
    "tvh_id": "MMOTOHD.es",
    "tvh_m3u": false,
    "tvh_nombre": "Movistar Moto GP HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "91195",
    "sd_nombre": "Movistar Series HD",
    "sd_numero": "",
    "tvh_id": "MSERHD.es",
    "tvh_m3u": false,
    "tvh_nombre": "Movistar Series HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "102941",
    "sd_nombre": "Movistar Seriesmanía HD",
    "sd_numero": "",
    "tvh_id": "MSERXHD.es",
    "tvh_m3u": false,
    "tvh_nombre": "Movistar Seriesmanía HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "90330",
    "sd_nombre": "MTV Dance",
    "sd_numero": "",
    "tvh_id": "MTVDAN.es",
    "tvh_m3u": false,
    "tvh_nombre": "MTV Dance",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "86934",
    "sd_nombre": "MTV España",
    "sd_numero": "",
    "tvh_id": "MTVESPA.es",
    "tvh_m3u": false,
    "tvh_nombre": "MTV España",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "109870",
    "sd_nombre": "MTV España HD",
    "sd_numero": "",
    "tvh_id": "MTVESHD.es",
    "tvh_m3u": false,
    "tvh_nombre": "MTV España HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "86935",
    "sd_nombre": "MTV Hits",
    "sd_numero": "",
    "tvh_id": "MTVHESP.es",
    "tvh_m3u": false,
    "tvh_nombre": "MTV Hits",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "90328",
    "sd_nombre": "MTV Music",
    "sd_numero": "",
    "tvh_id": "MTVMS.es",
    "tvh_m3u": false,
    "tvh_nombre": "MTV Music",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "90327",
    "sd_nombre": "MTV Rocks",
    "sd_numero": "",
    "tvh_id": "MTVROC.es",
    "tvh_m3u": false,
    "tvh_nombre": "MTV Rocks",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "84035",
    "sd_nombre": "Nat Geo Wild",
    "sd_numero": "",
    "tvh_id": "NATGWES.es",
    "tvh_m3u": false,
    "tvh_nombre": "Nat Geo Wild",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "91207",
    "sd_nombre": "Nat Geo Wild HD",
    "sd_numero": "",
    "tvh_id": "NGWSPHD.es",
    "tvh_m3u": false,
    "tvh_nombre": "Nat Geo Wild HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "86938",
    "sd_nombre": "National Geographic",
    "sd_numero": "",
    "tvh_id": "NGEOIB.es",
    "tvh_m3u": false,
    "tvh_nombre": "National Geographic",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "91208",
    "sd_nombre": "National Geographic HD",
    "sd_numero": "",
    "tvh_id": "NATGSHD.es",
    "tvh_m3u": false,
    "tvh_nombre": "National Geographic HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "78990",
    "sd_nombre": "Neox",
    "sd_numero": "",
    "tvh_id": "NEOX.es",
    "tvh_m3u": false,
    "tvh_nombre": "Neox",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "102754",
    "sd_nombre": "Neox HD",
    "sd_numero": "",
    "tvh_id": "NEOXHD.es",
    "tvh_m3u": false,
    "tvh_nombre": "Neox HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "90354",
    "sd_nombre": "Nick Jr.",
    "sd_numero": "",
    "tvh_id": "NICJRS.es",
    "tvh_m3u": false,
    "tvh_nombre": "Nick Jr.",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "109868",
    "sd_nombre": "Nick Jr. HD",
    "sd_numero": "",
    "tvh_id": "NJRSHD.es",
    "tvh_m3u": false,
    "tvh_nombre": "Nick Jr. HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "86939",
    "sd_nombre": "Nickelodeon",
    "sd_numero": "",
    "tvh_id": "NIKESP.es",
    "tvh_m3u": false,
    "tvh_nombre": "Nickelodeon",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "102755",
    "sd_nombre": "Nickelodeon +2 HD",
    "sd_numero": "",
    "tvh_id": "NIKE2HD.es",
    "tvh_m3u": false,
    "tvh_nombre": "Nickelodeon +2 HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "97469",
    "sd_nombre": "Nickelodeon HD",
    "sd_numero": "",
    "tvh_id": "NICHDES.es",
    "tvh_m3u": false,
    "tvh_nombre": "Nickelodeon HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "81786",
    "sd_nombre": "Nova",
    "sd_numero": "",
    "tvh_id": "NOVANT.es",
    "tvh_m3u": false,
    "tvh_nombre": "Nova",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "102944",
    "sd_nombre": "Nova HD",
    "sd_numero": "",
    "tvh_id": "NOVAEHD.es",
    "tvh_m3u": false,
    "tvh_nombre": "Nova HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "53785",
    "sd_nombre": "Odisea",
    "sd_numero": "",
    "tvh_id": "ODSEATV.es",
    "tvh_m3u": false,
    "tvh_nombre": "Odisea",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "91212",
    "sd_nombre": "Odisea HD",
    "sd_numero": "",
    "tvh_id": "ODISEHD.es",
    "tvh_m3u": false,
    "tvh_nombre": "Odisea HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "87049",
    "sd_nombre": "Paramount Network",
    "sd_numero": "",
    "tvh_id": "PARAESP.es",
    "tvh_m3u": false,
    "tvh_nombre": "Paramount Network",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "90337",
    "sd_nombre": "Playboy TV",
    "sd_numero": "",
    "tvh_id": "PLAYBES.es",
    "tvh_m3u": false,
    "tvh_nombre": "Playboy TV",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "109871",
    "sd_nombre": "Playboy TV HD",
    "sd_numero": "",
    "tvh_id": "PLBESHD.es",
    "tvh_m3u": false,
    "tvh_nombre": "Playboy TV HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "53930",
    "sd_nombre": "Real Madrid TV",
    "sd_numero": "",
    "tvh_id": "REALMDR.es",
    "tvh_m3u": false,
    "tvh_nombre": "Real Madrid TV",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "97484",
    "sd_nombre": "Real Madrid TV HD",
    "sd_numero": "",
    "tvh_id": "RMADHD.es",
    "tvh_m3u": false,
    "tvh_nombre": "Real Madrid TV HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "53993",
    "sd_nombre": "Sol Música",
    "sd_numero": "",
    "tvh_id": "SOLMUSC.es",
    "tvh_m3u": false,
    "tvh_nombre": "Sol Música",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "90363",
    "sd_nombre": "Somos",
    "sd_numero": "",
    "tvh_id": "SOMO.es",
    "tvh_m3u": false,
    "tvh_nombre": "Somos",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "102756",
    "sd_nombre": "Somos +2 HD",
    "sd_numero": "",
    "tvh_id": "SOMO2HD.es",
    "tvh_m3u": false,
    "tvh_nombre": "Somos +2 HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "102757",
    "sd_nombre": "Somos HD",
    "sd_numero": "",
    "tvh_id": "SOMOSHD.es",
    "tvh_m3u": false,
    "tvh_nombre": "Somos HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "102758",
    "sd_nombre": "Sundance +2 HD",
    "sd_numero": "",
    "tvh_id": "SUNE2HD.es",
    "tvh_m3u": false,
    "tvh_nombre": "Sundance +2 HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "91221",
    "sd_nombre": "Sundance HD",
    "sd_numero": "",
    "tvh_id": "SUNDAHD.es",
    "tvh_m3u": false,
    "tvh_nombre": "Sundance HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "86906",
    "sd_nombre": "SyFy Universal",
    "sd_numero": "",
    "tvh_id": "SYFYUE.es",
    "tvh_m3u": false,
    "tvh_nombre": "SyFy Universal",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "91222",
    "sd_nombre": "SyFy Universal HD",
    "sd_numero": "",
    "tvh_id": "SYFYSHD.es",
    "tvh_m3u": false,
    "tvh_nombre": "SyFy Universal HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "91223",
    "sd_nombre": "TCM HD",
    "sd_numero": "",
    "tvh_id": "TCMSPHD.es",
    "tvh_m3u": false,
    "tvh_nombre": "TCM HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "54015",
    "sd_nombre": "Telecinco",
    "sd_numero": "",
    "tvh_id": "TELECIN.es",
    "tvh_m3u": false,
    "tvh_nombre": "Telecinco",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "91224",
    "sd_nombre": "Telecinco HD",
    "sd_numero": "",
    "tvh_id": "TELECHD.es",
    "tvh_m3u": false,
    "tvh_nombre": "Telecinco HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "17189",
    "sd_nombre": "Teledeporte",
    "sd_numero": "",
    "tvh_id": "TDEP.es",
    "tvh_m3u": false,
    "tvh_nombre": "Teledeporte",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "91225",
    "sd_nombre": "Teledeporte HD",
    "sd_numero": "",
    "tvh_id": "TELEDHD.es",
    "tvh_m3u": false,
    "tvh_nombre": "Teledeporte HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "54025",
    "sd_nombre": "Telemadrid",
    "sd_numero": "",
    "tvh_id": "TELEMAD.es",
    "tvh_m3u": false,
    "tvh_nombre": "Telemadrid",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "91226",
    "sd_nombre": "Telemadrid HD",
    "sd_numero": "",
    "tvh_id": "TELEMHD.es",
    "tvh_m3u": false,
    "tvh_nombre": "Telemadrid HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "96791",
    "sd_nombre": "Televigo",
    "sd_numero": "",
    "tvh_id": "TELVIG.es",
    "tvh_m3u": false,
    "tvh_nombre": "Televigo",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "100496",
    "sd_nombre": "Ten",
    "sd_numero": "",
    "tvh_id": "TENESP.es",
    "tvh_m3u": false,
    "tvh_nombre": "Ten",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "86912",
    "sd_nombre": "TNT",
    "sd_numero": "",
    "tvh_id": "TNTESP.es",
    "tvh_m3u": false,
    "tvh_nombre": "TNT",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "102760",
    "sd_nombre": "TNT +2 HD",
    "sd_numero": "",
    "tvh_id": "TNTE2HD.es",
    "tvh_m3u": false,
    "tvh_nombre": "TNT +2 HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "91180",
    "sd_nombre": "TNT HD",
    "sd_numero": "",
    "tvh_id": "TNTSPHD.es",
    "tvh_m3u": false,
    "tvh_nombre": "TNT HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "91196",
    "sd_nombre": "Toros TV HD",
    "sd_numero": "",
    "tvh_id": "TOROSHD.es",
    "tvh_m3u": false,
    "tvh_nombre": "Toros TV HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "97480",
    "sd_nombre": "TPA HD",
    "sd_numero": "",
    "tvh_id": "TPAHD.es",
    "tvh_m3u": false,
    "tvh_nombre": "TPA HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "90342",
    "sd_nombre": "TPA7",
    "sd_numero": "",
    "tvh_id": "TPA7.es",
    "tvh_m3u": false,
    "tvh_nombre": "TPA7",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "87050",
    "sd_nombre": "Trece",
    "sd_numero": "",
    "tvh_id": "TRECEES.es",
    "tvh_m3u": false,
    "tvh_nombre": "Trece",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "86950",
    "sd_nombre": "TV Canaria",
    "sd_numero": "",
    "tvh_id": "TVCANAR.es",
    "tvh_m3u": false,
    "tvh_nombre": "TV Canaria",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "97472",
    "sd_nombre": "TV Canaria HD",
    "sd_numero": "",
    "tvh_id": "TVCANHD.es",
    "tvh_m3u": false,
    "tvh_nombre": "TV Canaria HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "87126",
    "sd_nombre": "TV3 HD",
    "sd_numero": "",
    "tvh_id": "TV3SPHD.es",
    "tvh_m3u": false,
    "tvh_nombre": "TV3 HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "87118",
    "sd_nombre": "TV5 Monde Europe",
    "sd_numero": "",
    "tvh_id": "TV5MDSP.es",
    "tvh_m3u": false,
    "tvh_nombre": "TV5 Monde Europe",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "90320",
    "sd_nombre": "TVE Internacional (Europe)",
    "sd_numero": "",
    "tvh_id": "TVEINTS.es",
    "tvh_m3u": false,
    "tvh_nombre": "TVE Internacional (Europe)",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "90400",
    "sd_nombre": "TVG",
    "sd_numero": "",
    "tvh_id": "TVGES.es",
    "tvh_m3u": false,
    "tvh_nombre": "TVG",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "90335",
    "sd_nombre": "TVG2",
    "sd_numero": "",
    "tvh_id": "TVG2.es",
    "tvh_m3u": false,
    "tvh_nombre": "TVG2",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "90326",
    "sd_nombre": "VH1",
    "sd_numero": "",
    "tvh_id": "VH1SPA.es",
    "tvh_m3u": false,
    "tvh_nombre": "VH1",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "102761",
    "sd_nombre": "VH1 +2",
    "sd_numero": "",
    "tvh_id": "VH1E2HD.es",
    "tvh_m3u": false,
    "tvh_nombre": "VH1 +2",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "54099",
    "sd_nombre": "Viajar",
    "sd_numero": "",
    "tvh_id": "VIAJAR1.es",
    "tvh_m3u": false,
    "tvh_nombre": "Viajar",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "87059",
    "sd_nombre": "Viajar HD",
    "sd_numero": "",
    "tvh_id": "VIAJARH.es",
    "tvh_m3u": false,
    "tvh_nombre": "Viajar HD",
    "tvh_tag": ""
  },
  {
    "sd_epg": false,
    "sd_fuente": "",
    "sd_id": "91182",
    "sd_nombre": "XTRM HD",
    "sd_numero": "",
    "tvh_id": "XTRMHD.es",
    "tvh_m3u": false,
    "tvh_nombre": "XTRM HD",
    "tvh_tag": ""
  }
];

export default cadenasFavoritos;